<?php
// $Id$

/**
 * @file
 * Enables the use of SMCF in Drupal.
 *
 * This module is for Drupal 6.x only.
 *
 * Module by: Eric Martin
 * Mailto: eric@ericmmartin.com
 */

/**
 * Implementation of hook_access().
 */
function smcf_access($op, $node, $account) {
	return user_access('administer SMCF');
}

/**
 * Implementation of hook_footer().
 */
function smcf_footer() {
	$output = "<div id='smcf-content' style='display:none'>
	<a href='#' title='Close' class='modalCloseX modalClose'>x</a>
	<div class='smcf-top'></div>
	<div class='smcf-content'>
		<h1 class='smcf-title'>" .  variable_get('smcf_form_title', 'Contact Me') . "</h1>
		<div class='smcf-loading' style='display:none'></div>
		<div class='smcf-message' style='display:none'></div>
		<form action='" . base_path() . "smcf/send' method='post' accept-charset='UTF-8'>
		<div>";

	// create the contact form HTML
	$output .= "
		<label for='smcf-name'>*" . t('Name') . ":</label>
		<input type='text' id='smcf-name' class='smcf-input' name='name' value='' tabindex='1001' />
		<label for='smcf-email'>*" . t('Email') . ":</label>
		<input type='text' id='smcf-email' class='smcf-input' name='email' value='' tabindex='1002' />";

	if (variable_get('smcf_form_subject', TRUE)) {
		$output .= "<label for='smcf-subject'>" . t('Subject') . ":</label>
		<input type='text' id='smcf-subject' class='smcf-input' name='subject' value='' tabindex='1003' />";
	}

	$output .= "<label for='smcf-message'>*" . t('Message') . ":</label>
		<textarea id='smcf-message' class='smcf-input' name='message' cols='40' rows='4' tabindex='1004'></textarea>";

	if (variable_get('smcf_form_cc_sender', TRUE)) {
		$output .= "<br/>
		<label>&nbsp;</label>
		<input type='checkbox' id='smcf-cc' name='cc' value='1' tabindex='1005' /> <span class='smcf-cc'>" . t('Send me a copy') . "</span>
		<br/>";
	}
	else {
		$output .= "<br/>";
	}

	$output .= "<label>&nbsp;</label>
		<button type='submit' class='smcf-button smcf-send' tabindex='1006'>" . t('Send') . "</button>
		<button type='submit' class='smcf-button smcf-cancel modalClose' tabindex='1007'>" . t('Cancel') . "</button>
		<input type='hidden' name='token' value=''/>
		<br/>
		</div>
		</form>";

	$output .= "</div>
	<div class='smcf-bottom'><a href='http://www.ericmmartin.com/projects/smcf-drupal/'>" . t('Powered by') . " SimpleModal Contact Form</a></div>
</div>";

	return $output;
}

/**
 * Implementation of hook_help().
 */
function smcf_help($path, $arg) {
	switch ($path) {
		case 'admin/modules#description':
			return t('Enables SMCF for Drupal');
		case 'admin/help#smcf':
			return t('<h3>Overview</h3>');
			break;
	}
}

/**
 * Implementation of hook_init().
 */
function smcf_init() {
	// Load required js and css files.
	$path = drupal_get_path('module', 'smcf');

	// Load the javascript settings.
	$js_settings = array(
		'images_url' => base_path() . $path . '/images/',
		'messages' => array(
			'loading' => t('Loading...'),
			'sending' => t('Sending...'),
			'thankyou' => t('Thank You!'),
			'error' => t('Uh oh...'),
			'goodbye' => t('Goodbye...'),
			'namerequired' => t('Name is required.'),
			'emailrequired' => t('Email is required.'),
			'emailinvalid' => t('Email is invalid.'),
			'messagerequired' => t('Message is required.')
		)
	);
	drupal_add_js(array('smcf' => $js_settings), 'setting');

	// load the CSS
	$css = $path .'/css/smcf.css';
	drupal_add_css($css);

	// Check where we should load the javascript files - header or footer.
	$js_location = variable_get('smcf_js_location', 'footer');
	if (variable_get('smcf_simplemodal_js', TRUE)) {
		drupal_add_js($path .'/js/jquery.simplemodal.js', 'module', $js_location);
	}
	drupal_add_js($path .'/js/smcf.js', 'module', $js_location);
}

/**
 * Implementation of hook_menu().
 */
function smcf_menu() {
	$items = array();

	$items['smcf/send'] = array(
		'title' => 'SMCF',
		'description' => 'Sends the contact form.',
		'page callback' => 'smcf_send_mail',
		'access arguments' => array('send email'),
		'type' => MENU_CALLBACK
	);

	$items['admin/settings/smcf'] = array(
		'title' => 'SMCF',
		'description' => 'Allows the user to configure the smcf settings',
		'file' => 'smcf.admin.inc',
		'page callback' => 'smcf_settings_page',
		'access callback' => 'user_access',
		'access arguments' => array('administer smcf'),
	);

	return $items;
}

/**
 * Implementation of hook_perm().
 */
function smcf_perm() {
	return array('administer SMCF');
}


/**
 * Custom menu callback
 */
function smcf_send_mail() {
	//drupal_mail('smcf', 'notify', $account->mail, user_preferred_language($account), $params);
	print "woo whoo";
}
