<?php
// $Id$

/**
 * @file
 * Enables the use of SMCF in Drupal.
 *
 * This module is for Drupal 6.x only.
 *
 * Module by: Eric Martin
 * Mailto: eric@ericmmartin.com
 */

/**
 * Implementation of hook_access().
 */
function smcf_access($op, $node, $account) {
  return user_access('administer smcf');
}

// Remove any un-safe values to prevent email injection
function smcf_filter($value) {
  $pattern = array("/\n/", "/\r/", "/content-type:/i", "/to:/i", "/from:/i", "/cc:/i");
  $value = preg_replace($pattern, "", $value);
  return $value;
}

/**
 * Implementation of hook_footer().
 */
function smcf_footer() {
  $to = variable_get('smcf_to_email', NULL);
  if (isset($to)) {
    $output = "<div id='smcf-content' style='display:none'>
    <a href='#' title='Close' class='modalCloseX modalClose'>x</a>
    <div class='smcf-top'></div>
    <div class='smcf-content'>
      <h1 class='smcf-title'>" . variable_get('smcf_form_title', 'Contact Me') . "</h1>
      <div class='smcf-loading' style='display:none'></div>
      <div class='smcf-message' style='display:none'></div>
      <form action='" . base_path() . "smcf/send' method='post' accept-charset='UTF-8' style='display:none'>
        <div>";

    // create the contact form HTML
    $output .= "
        <label for='smcf-name'>*" . t('Name') . ":</label>
        <input type='text' id='smcf-name' class='smcf-input' name='name' value='' tabindex='1001' />
        <label for='smcf-email'>*" . t('Email') . ":</label>
        <input type='text' id='smcf-email' class='smcf-input' name='email' value='' tabindex='1002' />";

    if (variable_get('smcf_form_subject', TRUE)) {
      $output .= "<label for='smcf-subject'>" . t('Subject') . ":</label>
        <input type='text' id='smcf-subject' class='smcf-input' name='subject' value='' tabindex='1003' />";
    }

    $output .= "<label for='smcf-message'>*" . t('Message') . ":</label>
        <textarea id='smcf-message' class='smcf-input' name='message' cols='40' rows='4' tabindex='1004'></textarea>";

    if (variable_get('smcf_form_cc_sender', TRUE)) {
      $output .= "<br/>
        <label>&nbsp;</label>
        <input type='checkbox' id='smcf-cc' name='cc' value='1' tabindex='1005' /> <span class='smcf-cc'>" . t('Send me a copy') . "</span>
        <br/>";
    }
    else {
      $output .= "<br/>";
    }

    $output .= "<label>&nbsp;</label>
        <button type='submit' class='smcf-button smcf-send' tabindex='1006'>" . t('Send') . "</button>
        <button type='submit' class='smcf-button smcf-cancel modalClose' tabindex='1007'>" . t('Cancel') . "</button>
        <input type='hidden' name='action' value='send'/>
        <input type='hidden' name='token' value='" . drupal_get_token() . "'/>
        <br/>
        </div>
      </form>";

    $output .= "</div>
    <div class='smcf-bottom'><a href='http://www.ericmmartin.com/projects/smcf-drupal/'>" . t('Powered by') . " SimpleModal Contact Form</a></div>
  </div>";
  }
  else {
    $output = '<!-- SMCF will not work until it has been configured -->';
  }
  return $output;
}

/**
 * Implementation of hook_help().
 */
function smcf_help($path, $arg) {
  switch ($path) {
    case 'admin/modules#description':
      return t('Enables SMCF for Drupal');
    case 'admin/help#smcf':
      return t('<h3>Overview</h3>
      <p align="justify">SimpleModal Contact Form (SMCF) is an Ajax powered modal contact form.</p>
      <p align="justify">It utilizes the jQuery JavaScript library and the SimpleModal jQuery plugin.</p>
      <p align="justify">SMCF has options to include the jQuery and SimpleModal files as well as whether to include certain contact form elements, like a Subject field and "Send me a copy" option for the sender.</p>
      <p align="justify">This module will include the CSS and JS files in your Drupal Installation without the need to edit your theme.</p>

      <h3>Requirements</h3>
      <ul>
		  <li>PHP mail()</li>
		  <li>jQuery 1.2 or greater</li>
		</ul>

      <h3>Installation</h3>
      <ol>
		  <li>Copy smcf folder to modules directory.</li>
		  <li>At admin/build/modules enable the SMCF module.</li>
		  <li>Enable permissions at admin/user/permissions.</li>
		  <li>Configure the module at admin/settings/smcf.</li>
		  <li>See "Adding SMCF Functionality to your site".</li>
		</ol>

      <h3>Adding SMCF Functionality To Your Site</h3>
      <p align="justify">After you\'ve installed, enabled and configured SMCF, you still need to integrate it into your site. There are two ways to make this happen:</p>
      <p align="justify">1. Add the class "smcf-link" to any element that you want to open SMCF (when clicked). For example: <br/>
<pre><code>&lt;a href="/contact" class="smcf-link"&gt;Contact&lt;/a&gt;</code></pre></p>
      <p align="justify">2. On the SMCF settings page, under Drupal Menu ID, enter the numeric ID for the menu item that you want SMCF to attach to (Do not include menu-). For example, if your theme produces:<br/>
<pre><code>&lt;ul class="links primary-links"&gt;
  &lt;li class="menu-112 first"&gt;&lt;a title="Contact" href="/drupal/node/1"&gt;Contact&lt;/a&gt;&lt;/li&gt;
&lt;/ul&gt;</code></pre>

You would enter <code>112</code> under Drupal Menu ID.</p>
<p>&nbsp;</p>
		');
      break;
  }
}

/**
 * Implementation of hook_init().
 */
function smcf_init() {
  $to = variable_get('smcf_to_email', NULL);
  if (isset($to)) {
    // Load required js and css files.
    $path = drupal_get_path('module', 'smcf');
    $menu_id = variable_get('smcf_menu_id', NULL);
    $selector = $menu_id ? ", .menu-$menu_id a" : "";

    // Load the javascript settings.
    $js_settings = array(
      'images_url' => base_path() . $path . '/images/',
      'selector' => $selector,
      'messages' => array(
        'loading' => t('Loading...'),
        'sending' => t('Sending...'),
        'thankyou' => t('Thank You!'),
        'error' => t('Uh oh...'),
        'goodbye' => t('Goodbye...'),
        'namerequired' => t('Name is required.'),
        'emailrequired' => t('Email is required.'),
        'emailinvalid' => t('Email is invalid.'),
        'messagerequired' => t('Message is required.')
      )
    );
    drupal_add_js(array('smcf' => $js_settings), 'setting');

    // load the CSS
    $css = $path .'/css/smcf.css';
    drupal_add_css($css);

    // Check where we should load the javascript files - header or footer.
    $js_location = variable_get('smcf_js_location', 'footer');
    if (variable_get('smcf_simplemodal_js', TRUE)) {
      drupal_add_js($path .'/js/jquery.simplemodal.js', 'module', $js_location);
    }
    drupal_add_js($path .'/js/smcf.js', 'module', $js_location);
  }
}

/**
 * Implementation of hook_mail().
 */
function smcf_mail($key, &$message, $params) {
  switch ($key) {
    case 'smcf_contact_email':
      $error = '';

      // make sure sender email is valid
      if (!valid_email_address($params['email'])) {
        $params['subject'] .= ' - invalid email';
        $error = t('Bad email: !email', array('!email' => $params['email']));
        $params['email'] = $message['to'];
        $params['cc'] = FALSE; // do not CC "sender"
      }

      // add cc header, if enabled and selected
      if (variable_get('smcf_form_cc_sender', TRUE) && $params['cc']) {
        $message['headers']['cc'] = $params['email'];
      }

      $message['headers']['from'] = $params['email'];
      $message['subject'] = $params['subject'];
      $message['body'][] = t('From: !name', array('!name' => $params['name']));
      $message['body'][] = t('Message: !message', array('!message' => $params['message']));
      
      if ($error) {
        $message['body'][] = $error;
      }

      // extra information
      if (variable_get('smcf_ip', FALSE)) {
        $message['body'][] = t('IP: !ip', array('!ip' => $_SERVER['REMOTE_ADDR']));
      }
      if (variable_get('smcf_ua', FALSE)) {
        $message['body'][] = t('USER AGENT: !ua', array('!ua' => $_SERVER['HTTP_USER_AGENT']));
      }
      break;
  }
}

/**
 * Implementation of hook_menu().
 */
function smcf_menu() {
  $items = array();

  $items['smcf/send'] = array(
    'title' => 'SMCF',
    'page callback' => 'smcf_send_mail',
    'access arguments' => array('administer smcf'),
    'type' => MENU_CALLBACK,
  );

  $items['admin/settings/smcf'] = array(
    'title' => 'SMCF',
    'description' => 'Allows the user to configure the smcf settings',
    'file' => 'smcf.admin.inc',
    'page callback' => 'smcf_settings_page',
    'access callback' => 'user_access',
    'access arguments' => array('administer smcf'),
  );

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function smcf_perm() {
  return array('administer smcf');
}


/**
 * Custom menu callback
 */
function smcf_send_mail() {
  $result = '';

  $action = isset($_POST['action']) ? $_POST['action'] : '';
  if ($action == 'send') {
    // validate mail
    $token = isset($_POST['token']) ? $_POST['token'] : NULL;
    if (drupal_valid_token($token)) {
      // get post variables
      $params = array();
      $params['name'] = isset($_POST['name']) ? smcf_filter($_POST['name']) : NULL;
      $params['email'] = isset($_POST['email']) ? smcf_filter($_POST['email']) : NULL;
      $params['subject'] = isset($_POST['subject']) ? smcf_filter($_POST['subject']) : variable_get('smcf_subject', 'SimpleModal Contact Form');
      $params['message'] = isset($_POST['message']) ? $_POST['message'] : NULL;
      $params['cc'] = isset($_POST['cc']) ? $_POST['cc'] : NULL;

      $to = variable_get('smcf_to_email', NULL);
      if (isset($to)) {
        $mail = drupal_mail('smcf', 'smcf_contact_email', $to, language_default(), $params, $params['email']);
        $result = $mail['result'] ? 
          t('Your message was successfully sent.') : 
          t('Unfortunately, a server issue prevented delivery of your message.');
      }
      else {
        watchdog('smcf', "Invalid email: $to");
        $result = t('Unfortunately, a configuration issue prevented delivery of your message.');
      }
    }
    else {
      $result = t('Unfortunately, your message could not be verified.');
    }
  }
  else {
    // intentionally left blank in case someone tries to directly access this url
  }
  echo $result;
}
